# Import the relevant libraries

In [2]:
import numpy as np

# Declaring scalars, vectors, and matrices

## Scalars

In [2]:
s = 5

In [3]:
s

5

## Vectors

In [4]:
v = np.array([5,-2,4])

In [5]:
v

array([ 5, -2,  4])

## Matrices

In [6]:
m = np.array([[5,12,6],[-3,0,14]])

In [7]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

## Data types

In [8]:
type(s)

int

In [9]:
type(v)

numpy.ndarray

In [10]:
type(m)

numpy.ndarray

In [11]:
s_array = np.array([5])

In [12]:
type(s_array)

numpy.ndarray

## Data shapes

In [13]:
m.shape

(2, 3)

In [14]:
v.shape

(3,)

In [15]:
s.shape

AttributeError: 'int' object has no attribute 'shape'

In [16]:
s_array.shape

(1,)

## Creating a column vector

In [17]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [18]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [19]:
m+s

array([[10, 17, 11],
       [ 2,  5, 19]])

In [20]:
m+s_array

array([[10, 17, 11],
       [ 2,  5, 19]])

In [21]:
v+s

array([10,  3,  9])

In [22]:
v

array([ 5, -2,  4])

In [23]:
v+s_array

array([10,  3,  9])

In [24]:
m+v

array([[10, 10, 10],
       [ 2, -2, 18]])

## Addition

#### Task 1: Write below the code for adding the following matrices:

5,12,6
-3,0,14

9,8,7
1,3,-5

Sol
1. initialised array a and b
2. added them using '+' operator

In [3]:
a=np.array([[5,12,6],[-3,0,14]])
b=np.array([[9,8,7],[1,3,-5]])
a+b

array([[14, 20, 13],
       [-2,  3,  9]])

## Difference

#### Task 2: Write below the code for substracting the following matrices:

5,3
-2,4

7,-5
3,8

Sol
1. initialised array c and d
2. subtracted d from c using '-' operator

In [6]:
c=np.array([[5,3],[-2,4]])
d=np.array([[7,-5],[3,8]])
c-d

array([[-2,  8],
       [-5, -4]])

## Adding vectors together

#### Task 3: Write below the code for adding and substracting the following vectors:
{1,2,3,4,5} and {5,4,3,2,1} 

Sol
1. intitialise e and f vectors
2. set g as e+f and h as e-f
3. print g and h

In [7]:
e=np.array([1,2,3,4,5])
f=np.array([5,4,3,2,1])
g=e+f
h=e-f
print(g,h)

[6 6 6 6 6] [-4 -2  0  2  4]


## Vector * Vector

In [ ]:
x = np.array([2,8,-4])
y = np.array([1,-7,3])

In [ ]:
np.dot(x,y)

In [ ]:
u = np.array([0,2,5,8])
v = np.array([20,3,4,-1])

In [ ]:
np.dot(u,v)

## Scalar * Scalar

#### Task 4: Write the code below to calculate the dot product of the scalar values [10] and [-2]

Sol:
    Can be done in two ways either using np.dot function or * operator

In [8]:
np.dot(10,2)

20

In [9]:
10*2

20

## Scalar * Vector

In [ ]:
5*x

## Scalar * Matrix

####   Task 5: Write the code for the multiplication of [3] with matrix:

5,12,6
-3,0,14

Sol
1. Intialise array i
2. Can be multiplied using dot product or * operator

In [13]:
i=np.array([[5,12,6],[-3,0,14]])

In [14]:
3*i

array([[15, 36, 18],
       [-9,  0, 42]])

In [12]:
np.dot(3,i)

array([[15, 36, 18],
       [-9,  0, 42]])

## Matrix * Matrix

#### Task 6: Write the code for the multiplication of the previous matrix (task 5) with the following one:

[2,-1],[8,0],[3,0]]

## Transposing matrices

In [2]:
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [3]:
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [4]:
B = np.array([[5,3],[-2,4]])
B

array([[ 5,  3],
       [-2,  4]])

In [5]:
B.T

array([[ 5, -2],
       [ 3,  4]])

In [6]:
C = np.array([[4,-5],[8,12],[-2,-3],[19,0]])
C

array([[ 4, -5],
       [ 8, 12],
       [-2, -3],
       [19,  0]])

In [7]:
C.T

array([[ 4,  8, -2, 19],
       [-5, 12, -3,  0]])

## Transposing scalars

In [8]:
s = np.array([5])

In [9]:
s.T

array([5])

## Transposing vectors

#### Task 6.1: Write the code below to transpore vector (1 2 3) and get it back to its original shape and format

Sol
1. intialise j
2. use .T function to transpose

In [16]:
j=np.array([1,2,3])
j.T

array([1, 2, 3])

### Addition of scalars

In [2]:
5 + 5

10

In [3]:
10 - 4

6

### Addition of matrices

In [20]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [21]:
m3 = np.array([[5,3],[-2,4]])
m3

array([[ 5,  3],
       [-2,  4]])

In [22]:
m1 + m3

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

Sol
1. make m1 and m3 equal by adding 0 in the end of m3.(there could be different solutions too)

In [23]:
m3 = np.array([[5,3,0],[-2,4,0]])
m3

array([[ 5,  3,  0],
       [-2,  4,  0]])

In [24]:
m1+m3

array([[10, 15,  6],
       [-5,  4, 14]])

#### Task 7: Identify and fix the error above.

### Addition of vectors

In [27]:
v1 = np.array([1,2,3,4,5])
v1

array([1, 2, 3, 4, 5])

In [28]:
v3 = np.array([1,2,3])
v3

array([1, 2, 3])

In [29]:
v1+v3

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

Sol:
Like the previous add 0,0 to v3 to balance both

In [30]:
v3=np.array([1,2,3,0,0])
v3

array([1, 2, 3, 0, 0])

In [31]:
v1+v3

array([2, 4, 6, 4, 5])

#### Task 8: Identify and fix the error above.

#### Task 9: Write the code below to increase every single element in hte folwooing matrix by 1:

5, 12,  6
-3,  0, 14

Sol
1. create matrix k
2. just add 1 to k to get the solution

In [34]:
k=np.array([[5,12,6],[-3,0,14]])
k

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [35]:
k+1

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [37]:
# create an 5x5 identiy matrix
I = np.eye(5)

# define a square matrix full rank
A = np.array([
    [1,4],
    [5,9]
])

# compute the inverse
A_inverse = np.linalg.inv(A)

In [38]:
A_inverse

array([[-0.81818182,  0.36363636],
       [ 0.45454545, -0.09090909]])

In [39]:
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
from numpy import linalg as LA

#### Task 10: Visit the NumPy API documentation for Liner Algebra as available by the URL
https://numpy.org/doc/stable/reference/routines.linalg.html 
#### Subsequently, write the code to calculate the eigen-value and eigen-vectors of the array A above.

Sol : 
Use LA.eig() function to calculate eigen value and eigen vector of A

In [43]:
eig_val, eig_vec = LA.eig(A)

In [44]:
eig_val #eigen value of A

array([-1., 11.])

In [45]:
eig_vec #eigen vectors of A

array([[-0.89442719, -0.37139068],
       [ 0.4472136 , -0.92847669]])