# Import the relevant libraries

#### Visit the NumPy API documentation for Liner Algebra as available by the URL
https://numpy.org/doc/stable/reference/routines.linalg.html 


In [34]:
import numpy as np

#### Task 1: Write a program to resolve the following system of linear equations based on the calculation of an inverse matrix:
#### 2x-y+2x=10
#### x-2y+z=8
#### 3x-y+2z=11


In [42]:
#intialise A and B
A=np.array([[2,-1,2],[1,-2,1],[3,-1,2]])
B=np.array([10,8,11])

In [43]:
#use linalg.inv() function to find inverse
A_inv = linalg.inv(A)
A_inv

array([[-1.00000000e+00,  0.00000000e+00,  1.00000000e+00],
       [ 3.33333333e-01, -6.66666667e-01,  1.11022302e-17],
       [ 1.66666667e+00, -3.33333333e-01, -1.00000000e+00]])

In [45]:
# X = A inverse * B
# using np.dot() function to find the solution 
X = np.dot(A_inv,B)
X

array([ 1., -2.,  3.])

#### Task 2: Use the linalg.solve library and function to solve the system of 3 equations above in an alternative way (no need to calculate the inverse of the coefficients matrix m) 

In [46]:
#use linalg.solve() to find solution in one go
linalg.solve(A,B)

array([ 1., -2.,  3.])

#### Task 3: Use the same linalg.solve library and function to solve a system of 4 equations by adding the following equation to the previous 3 ones. Adjust the previous system of equations in such a way that the problem can be resolved.

#### 3x-2y-z+4w=-3

In [47]:
#added 0 to end of first three equations since w=0 in those three equations
A=np.array([[2,-1,2,0],[1,-2,1,0],[3,-1,2,0],[3,-2,-1,4]])
B=B=np.array([10,8,11,-3])

In [48]:
#displaying array A and B
A,B

(array([[ 2, -1,  2,  0],
        [ 1, -2,  1,  0],
        [ 3, -1,  2,  0],
        [ 3, -2, -1,  4]]),
 array([10,  8, 11, -3]))

In [50]:
#used linalg.solve() to find solution
linalg.solve(A,B)

array([ 1.  , -2.  ,  3.  , -1.75])